elkarbackup:
  image: elkarbackup/elkarbackup:1.2.6
  links:
    - db:mysql
  environment:
    MYSQL_ROOT_PASSWORD: changeme
  ports:
    - ${public_port}:80

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: changeme
