.catalog:
  name: "ElkarBackup"
  version: "v0.2"
  description: "Open source backup solution for your network"
  uuid: ElkarBackup-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access ElkarBackup web UI"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"


elkarbackup:
