version: '2'
catalog:
  name: "ElkarBackup"
  version: "v1.2.6-rancher1"
  description: "Open source backup solution for your network"
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access ElkarBackup web UI"
      label: "Public Port"
      required: true
      default: "80"
      type: "int" 
