version: '2'
catalog:
  name: "ElkarBackup"
  version: "v1.2.6-rancher1"
  description: "Open source backup solution for your network"
  minimum_rancher_version: v0.51.0
  upgrade_from: "0.1"
  questions:
    - variable: public_port
      description: "public port to access ElkarBackup web UI"
      label: "Public Port"
      required: true
      default: "80"
      type: "int" 
    - variable: mysql_root_password
      description: "MySQL root password"
      label: "MySQL password"
      default: "changeme"
      type: "password"
    - variable: disable_cron
      description: "Disable CRON service"
      label: "Disable CRON"
      type: "boolean"
      default: "true"
