version: '2'
catalog:
  name: "ElkarBackup"
  version: "v1.2.7-rancher2"
  description: "Open source backup solution for your network"
  minimum_rancher_version: v0.51.0
  upgrade_from: "v1.2.6-rancher1"
  questions:
    - variable: public_port
      description: "public port to access ElkarBackup web UI"
      label: "Public Port"
      required: true
      default: "80"
      type: "int" 
    - variable: mysql_root_password
      description: "MySQL root password"
      label: "MySQL password"
      default: "changeme"
      type: "password"
    - variable: disable_cron
      description: "Disable CRON service"
      label: "Disable CRON"
      type: "boolean"
      default: "false"
    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
