name: Elkarbackup
description: |
  Open source backup solution for your network
version: v0.1
category: Security
maintainer: Xabi Ezpeleta <xezpeleta@gmail.com>
license: New-BSD
projectURL: http://www.elkarbackup.org
